# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: benzz
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ben3point6app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ce6-sls-ben

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  benfunc:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
      - sqs:
          arn: arn:aws:sqs:ap-southeast-1:255945442255:ben-sqs-sept
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures
          
plugins:
  - serverless-offline